### ISSUE TITLE
Why is this plugin deprecated??

### ISSUE THREAD

**Issue by blackjid** [rbenv/rbenv-gem-rehash#17]
The github description says DEPRECATED. Why?
Is there any alternative to this??

**Comment by arianon** [comment]
:+1:

**Comment by ssaunier** [comment]
Wondering the same.

**Comment by born4new** [comment]
Have a look at this: https://github.com/rbenv/rbenv-gem-rehash/pull/16

**Comment by blackjid** [comment]
Thanks!!!, that makes a lot of sense....

**Comment by blackjid** [comment]
It really looks that I should have done a better search for the answer :grin: 
https://github.com/rbenv/rbenv/pull/638 and https://github.com/rbenv/rbenv-gem-rehash/pull/16 are pretty old..
